/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.51
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The FileInfo model module.
 * @module model/FileInfo
 * @version v0
 */
export class FileInfo {
  /**
   * Constructs a new <code>FileInfo</code>.
   * @alias module:model/FileInfo
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>FileInfo</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/FileInfo} obj Optional instance to populate.
   * @return {module:model/FileInfo} The populated <code>FileInfo</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new FileInfo();
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('type'))
        obj.type = ApiClient.convertToType(data['type'], 'String');
      if (data.hasOwnProperty('size'))
        obj.size = ApiClient.convertToType(data['size'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} name
 */
FileInfo.prototype.name = undefined;

/**
 * @member {String} type
 */
FileInfo.prototype.type = undefined;

/**
 * @member {String} size
 */
FileInfo.prototype.size = undefined;

