/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.51
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The UploadBody model module.
 * @module model/UploadBody
 * @version v0
 */
export class UploadBody {
  /**
   * Constructs a new <code>UploadBody</code>.
   * @alias module:model/UploadBody
   * @class
   * @param file {Blob} 
   */
  constructor(file) {
    this.file = file;
  }

  /**
   * Constructs a <code>UploadBody</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UploadBody} obj Optional instance to populate.
   * @return {module:model/UploadBody} The populated <code>UploadBody</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new UploadBody();
      if (data.hasOwnProperty('File'))
        obj.file = ApiClient.convertToType(data['File'], 'Blob');
    }
    return obj;
  }
}

/**
 * @member {Blob} file
 */
UploadBody.prototype.file = undefined;

